name: Upload Artifact

on: workflow_dispatch

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run : echo "Coucou" > artifact.txt
      - name: uplodad artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt

  download:
    name: download
    runs-on: ubuntu-latest
    steps:
      - name: download file
        uses: actions/downlad-artifact@v3
        with:
          name: artifact
      - name: read-file
        run: cat artifact.txt