name: Hello Alex
# Event trigger qui implique de déclencher le worklow à la main
on: workflow_dispatch

env:
  NAME: Alex

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Dit bonjour"
        if: ${{ env.NAME != 'Alex' }}
        run: echo "Salut toi ! Tu n'es pas Alex ?! oO"
      - name: "Coucou Alex"
        if: ${{ env.NAME == 'Alex' }}
<<<<<<< HEAD
        run: echo "Salut $NAME ! Tu as l'air en pleine forme !"
=======
        run: echo "Salut $NAME ! Tu as l'air en pleine forme !"
>>>>>>> 75b0f58c3b89f19190046daed286018aeca0335b
