name: fruits

on: workflow_dispatch

jobs:
  fruitz:
    strategy:
      fail-fast: true
      matrix:
        fruits: [Pomme, Poire, Pêche, Cerise]
        personnes: [Alex, Killian, Antoine, Adrien]
    name: Fruitz
    runs-on: ubuntu-latest
    steps:
      - name: Goutez
        env:
          FRUIT: ${{matrix.fruits}}
          NOM: ${{matrix.personnes}}
        run : echo "${{matrix.personnes}} mange une ${{matrix.fruits}}, et il adore ça !"